"""db_creation

Revision ID: ff27520d987f
Revises: 
Create Date: 2024-05-06 16:25:10.826602

"""
import random

import faker
import sqlalchemy as sa
from alembic import op

fake = faker.Faker()

# revision identifiers, used by Alembic.
revision = "ff27520d987f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    full_name = op.create_table(
        "full_name",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("status", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    short_name = op.create_table(
        "short_name",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("status", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
    op.bulk_insert(
        full_name,
        [
            {"name": "name" + str(i) + "." + fake.file_extension(), "status": None}
            for i in range(500_000)
        ],
    )
    op.bulk_insert(
        short_name,
        [
            {"name": "name" + str(i), "status": random.choice([0, 1])}
            for i in range(700_000)
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("short_name")
    op.drop_table("full_name")
    # ### end Alembic commands ###
