version: '3.9'
services:

  postgres:
    restart: always
    image: postgres:15.3-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

  alembic:
    build: .
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  postgres-data:
